name: README build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Update README
        run: |
          # Set timezone to Bangladesh Standard Time (GMT+6)
          export TZ="Asia/Dhaka"
          # Get the formatted date string, e.g., "Friday, September 19 at 04:29 PM GMT+6"
          DATE_STR=$(date +"%A, %B %d at %I:%M %p %Z")
          # Replace the {date} placeholder in the template and output to README.adoc
          sed "s/{date}/$DATE_STR/g" template.adoc > README.adoc
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "docs: auto-update README.adoc"
          file_pattern: README.adoc
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
